"""empty message

Revision ID: 61906c3f1b56
Revises:
Create Date: 2018-11-02 10:47:31.355610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61906c3f1b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
